package leaf.component.mongoautogenerated;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@NoArgsConstructor
@AllArgsConstructor
@Getter @Setter
@Builder
@Document(collection = "sequence")
public class ChatMessageSequence {

   @Id
   private String id;
   private Long seq;

}
