package leaf.service.chat;

import leaf.component.mongoautogenerated.SequenceGenerator;
import leaf.model.dao.chat.ChatMessageRepository;
import leaf.model.dto.chat.ChatMessage;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@AllArgsConstructor
@Service
public class ChatMessageService {

    ChatMessageRepository repo;
    SequenceGenerator sequenceGenerator;

    public List<ChatMessage> getAllMessage(Long roomIdx) {
        return repo.findAllByRoomIdxOrderByCreatedAtDesc(roomIdx);
    }

    public void putMessage(ChatMessage message) {
        message.set_id(sequenceGenerator.getNextSequenceId(SequenceGenerator.SEQ_KEY));
        message.setCreatedAt(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        repo.insert(message);
    }

}
