package leaf.service.chat;

import leaf.component.mongoautogenerated.SequenceGenerator;
import leaf.model.dao.chat.ChatMessageRepository;
import leaf.model.dto.chat.ChatMessage;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@AllArgsConstructor
@Service
public class ChatMessageService {

    ChatMessageRepository repo;
    SequenceGenerator sequenceGenerator;

    public List<ChatMessage> getAllMessage(Long roomIdx) {
        return repo.findAllByRoomIdxOrderByCreatedAt(roomIdx);
    }

    public void putMessage(ChatMessage message) {
        message.setId(sequenceGenerator.getNextSequenceId(SequenceGenerator.SEQ_KEY));
        message.setCreatedAt(LocalDateTime.now());
        repo.insert(message);
    }

}
